namespace :db do

  task seed_locations: :environment do
    county = County.create(name: 'I ZAGREBAČKA')
    City.create(name: 'Bedenica', county: county)
    City.create(name: 'Bistra', county: county)
    City.create(name: 'Brckovljani', county: county)
    City.create(name: 'Brdovec', county: county)
    City.create(name: 'Dubrava', county: county)
    City.create(name: 'Dubravica', county: county)
    City.create(name: 'Dugo Selo', county: county)
    City.create(name: 'Farkaševac', county: county)
    City.create(name: 'Gradec', county: county)
    City.create(name: 'Ivanić-Grad', county: county)
    City.create(name: 'Jakovlje', county: county)
    City.create(name: 'Jastrebarsko', county: county)
    City.create(name: 'Klinča Sela', county: county)
    City.create(name: 'Kloštar Ivanić', county: county)
    City.create(name: 'Krašić', county: county)
    City.create(name: 'Kravarsko', county: county)
    City.create(name: 'Križ', county: county)
    City.create(name: 'Luka', county: county)
    City.create(name: 'Marija Gorica', county: county)
    City.create(name: 'Orle', county: county)
    City.create(name: 'Pisarovina', county: county)
    City.create(name: 'Pokupsko', county: county)
    City.create(name: 'Preseka', county: county)
    City.create(name: 'Pušća', county: county)
    City.create(name: 'Rakovec', county: county)
    City.create(name: 'Rugvica', county: county)
    City.create(name: 'Samobor', county: county)
    City.create(name: 'Stupnik', county: county)
    City.create(name: 'Sveta Nedelja', county: county)
    City.create(name: 'Sveti Ivan Zelina', county: county)
    City.create(name: 'Velika Gorica', county: county)
    City.create(name: 'Vrbovec', county: county)
    City.create(name: 'Zaprešić', county: county)
    City.create(name: 'Žumberak', county: county)
    county = County.create(name: 'II KRAPINSKO-ZAGORSKA')
    City.create(name: 'Bedekovčina', county: county)
    City.create(name: 'Budinščina', county: county)
    City.create(name: 'Desinić', county: county)
    City.create(name: 'Donja Stubica', county: county)
    City.create(name: 'Đurmanec', county: county)
    City.create(name: 'Gornja Stubica', county: county)
    City.create(name: 'Hrašćina', county: county)
    City.create(name: 'Hum na Sutli', county: county)
    City.create(name: 'Jesenje', county: county)
    City.create(name: 'Klanjec', county: county)
    City.create(name: 'Konjščina', county: county)
    City.create(name: 'Kraljevec na Sutli', county: county)
    City.create(name: 'Krapina', county: county)
    City.create(name: 'Krapinske Toplice', county: county)
    City.create(name: 'Kumrovec', county: county)
    City.create(name: 'Lobor', county: county)
    City.create(name: 'Mače', county: county)
    City.create(name: 'Marija Bistrica', county: county)
    City.create(name: 'Mihovljan', county: county)
    City.create(name: 'Novi Golubovec', county: county)
    City.create(name: 'Oroslavje', county: county)
    City.create(name: 'Petrovsko', county: county)
    City.create(name: 'Pregrada', county: county)
    City.create(name: 'Radoboj', county: county)
    City.create(name: 'Stubičke Toplice', county: county)
    City.create(name: 'Sveti Križ Začretje', county: county)
    City.create(name: 'Tuhelj', county: county)
    City.create(name: 'Veliko Trgovišće', county: county)
    City.create(name: 'Zabok', county: county)
    City.create(name: 'Zagorska Sela', county: county)
    City.create(name: 'Zlatar', county: county)
    City.create(name: 'Zlatar Bistrica', county: county)
    county = County.create(name: 'III SISAČKO-MOSLAVAČKA')
    City.create(name: 'Donji Kukuruzari', county: county)
    City.create(name: 'Dvor', county: county)
    City.create(name: 'Glina', county: county)
    City.create(name: 'Gvozd', county: county)
    City.create(name: 'Hrvatska Dubica', county: county)
    City.create(name: 'Hrvatska Kostajnica', county: county)
    City.create(name: 'Jasenovac', county: county)
    City.create(name: 'Kutina', county: county)
    City.create(name: 'Lekenik', county: county)
    City.create(name: 'Lipovljani', county: county)
    City.create(name: 'Majur', county: county)
    City.create(name: 'Martinska Ves', county: county)
    City.create(name: 'Novska', county: county)
    City.create(name: 'Petrinja', county: county)
    City.create(name: 'Popovača', county: county)
    City.create(name: 'Sisak', county: county)
    City.create(name: 'Sunja', county: county)
    City.create(name: 'Topusko', county: county)
    City.create(name: 'Velika Ludina', county: county)
    county = County.create(name: 'IV KARLOVAČKA')
    City.create(name: 'Barilović', county: county)
    City.create(name: 'Bosiljevo', county: county)
    City.create(name: 'Cetingrad', county: county)
    City.create(name: 'Draganić', county: county)
    City.create(name: 'Generalski Stol', county: county)
    City.create(name: 'Josipdol', county: county)
    City.create(name: 'Kamanje', county: county)
    City.create(name: 'Krnjak', county: county)
    City.create(name: 'Lasinja', county: county)
    City.create(name: 'Netretić', county: county)
    City.create(name: 'Plaški', county: county)
    City.create(name: 'Rakovica', county: county)
    City.create(name: 'Ribnik', county: county)
    City.create(name: 'Saborsko', county: county)
    City.create(name: 'Tounj', county: county)
    City.create(name: 'Vojnić', county: county)
    City.create(name: 'Žakanje', county: county)
    City.create(name: 'Duga Resa', county: county)
    City.create(name: 'Karlovac', county: county)
    City.create(name: 'Ogulin', county: county)
    City.create(name: 'Ozalj', county: county)
    City.create(name: 'Slunj', county: county)
    county = County.create(name: 'IX LIČKO-SENJSKA')
    City.create(name: 'Brinje', county: county)
    City.create(name: 'Donji Lapac', county: county)
    City.create(name: 'Gospić', county: county)
    City.create(name: 'Karlobag', county: county)
    City.create(name: 'Lovinac', county: county)
    City.create(name: 'Novalja', county: county)
    City.create(name: 'Otočac', county: county)
    City.create(name: 'Perušić', county: county)
    City.create(name: 'Plitvička Jezera', county: county)
    City.create(name: 'Senj', county: county)
    City.create(name: 'Udbina', county: county)
    City.create(name: 'Vrhovine', county: county)
    county = County.create(name: 'V VARAŽDINSKA')
    City.create(name: 'Bednja', county: county)
    City.create(name: 'Beretinec', county: county)
    City.create(name: 'Breznica', county: county)
    City.create(name: 'Breznički Hum', county: county)
    City.create(name: 'Cestica', county: county)
    City.create(name: 'Donja Voća', county: county)
    City.create(name: 'Gornji Kneginec', county: county)
    City.create(name: 'Jalžabet', county: county)
    City.create(name: 'Ivanec', county: county)
    City.create(name: 'Klenovnik', county: county)
    City.create(name: 'Ljubešćica', county: county)
    City.create(name: 'Lepoglava', county: county)
    City.create(name: 'Ludbreg', county: county)
    City.create(name: 'Mali Bukovec', county: county)
    City.create(name: 'Martijanec', county: county)
    City.create(name: 'Maruševec', county: county)
    City.create(name: 'Novi Marof', county: county)
    City.create(name: 'Petrijanec', county: county)
    City.create(name: 'Sračinec', county: county)
    City.create(name: 'Sveti Đurđ', county: county)
    City.create(name: 'Sveti Ilija', county: county)
    City.create(name: 'Trnovec Bartolovečki', county: county)
    City.create(name: 'Varaždin', county: county)
    City.create(name: 'Varaždinske Toplice', county: county)
    City.create(name: 'Veliki Bukovec', county: county)
    City.create(name: 'Vidovec', county: county)
    City.create(name: 'Vinica', county: county)
    City.create(name: 'Visoko', county: county)
    county = County.create(name: 'VI KOPRIVNIČKO-KRIŽEVAČKA')
    City.create(name: 'Drnje', county: county)
    City.create(name: 'Đelekovec', county: county)
    City.create(name: 'Đurđevac', county: county)
    City.create(name: 'Ferdinandovac', county: county)
    City.create(name: 'Gola', county: county)
    City.create(name: 'Gornja Rijeka', county: county)
    City.create(name: 'Hlebine', county: county)
    City.create(name: 'Kalinovac', county: county)
    City.create(name: 'Kalnik', county: county)
    City.create(name: 'Kloštar Podravski', county: county)
    City.create(name: 'Koprivnički Bregi', county: county)
    City.create(name: 'Koprivnica', county: county)
    City.create(name: 'Koprivnički Ivanec', county: county)
    City.create(name: 'Legrad', county: county)
    City.create(name: 'Molve', county: county)
    City.create(name: 'Novigrad Podravski', county: county)
    City.create(name: 'Novo Virje', county: county)
    City.create(name: 'Peteranec', county: county)
    City.create(name: 'Podravske Sesvete', county: county)
    City.create(name: 'Rasinja', county: county)
    City.create(name: 'Sokolovac', county: county)
    City.create(name: 'Sveti Ivan Žabno', county: county)
    City.create(name: 'Sveti Petar Orehovec', county: county)
    City.create(name: 'Virje', county: county)
    City.create(name: 'Križevci', county: county)
    county = County.create(name: 'VII BJELOVARSKO-BILOGORSKA')
    City.create(name: 'Berek', county: county)
    City.create(name: 'Bjelovar', county: county)
    City.create(name: 'Čazma', county: county)
    City.create(name: 'Daruvar', county: county)
    City.create(name: 'Dežanovac', county: county)
    City.create(name: 'Đulovac', county: county)
    City.create(name: 'Garešnica', county: county)
    City.create(name: 'Grubišno Polje', county: county)
    City.create(name: 'Hercegovac', county: county)
    City.create(name: 'Ivanska', county: county)
    City.create(name: 'Kapela', county: county)
    City.create(name: 'Končanica', county: county)
    City.create(name: 'Nova Rača', county: county)
    City.create(name: 'Rovišće', county: county)
    City.create(name: 'Severin', county: county)
    City.create(name: 'Sirač', county: county)
    City.create(name: 'Šandrovac', county: county)
    City.create(name: 'Štefanje', county: county)
    City.create(name: 'Velika Pisanica', county: county)
    City.create(name: 'Velika Trnovitica', county: county)
    City.create(name: 'Veliki Grđevac', county: county)
    City.create(name: 'Veliko Trojstvo', county: county)
    City.create(name: 'Zrinski Topolovac', county: county)
    county = County.create(name: 'VIII PRIMORSKO-GORANSKA')
    City.create(name: 'Bakar', county: county)
    City.create(name: 'Baška', county: county)
    City.create(name: 'Brod Moravice', county: county)
    City.create(name: 'Cres', county: county)
    City.create(name: 'Crikvenica', county: county)
    City.create(name: 'Čabar', county: county)
    City.create(name: 'Čavle', county: county)
    City.create(name: 'Delnice', county: county)
    City.create(name: 'Dobrinj', county: county)
    City.create(name: 'Fužine', county: county)
    City.create(name: 'Jelenje', county: county)
    City.create(name: 'Kastav', county: county)
    City.create(name: 'Klana', county: county)
    City.create(name: 'Kostrena', county: county)
    City.create(name: 'Kraljevica', county: county)
    City.create(name: 'Krk', county: county)
    City.create(name: 'Lokve', county: county)
    City.create(name: 'Lopar', county: county)
    City.create(name: 'Lovran', county: county)
    City.create(name: 'Mali Lošinj', county: county)
    City.create(name: 'Malinska-Dubašnica', county: county)
    City.create(name: 'Matulji', county: county)
    City.create(name: 'Mošćenička Draga', county: county)
    City.create(name: 'Mrkopalj', county: county)
    City.create(name: 'Novi Vinodolski', county: county)
    City.create(name: 'Omišalj', county: county)
    City.create(name: 'Opatija', county: county)
    City.create(name: 'Punat', county: county)
    City.create(name: 'Rab', county: county)
    City.create(name: 'Ravna Gora', county: county)
    City.create(name: 'Rijeka', county: county)
    City.create(name: 'Skrad', county: county)
    City.create(name: 'Vinodolska općina', county: county)
    City.create(name: 'Viškovo', county: county)
    City.create(name: 'Vrbnik', county: county)
    City.create(name: 'Vrbovsko', county: county)
    county = County.create(name: 'X VIROVITIČKO-PODRAVSKA')
    City.create(name: 'Crnac', county: county)
    City.create(name: 'Čačinci', county: county)
    City.create(name: 'Čađavica', county: county)
    City.create(name: 'Gradina', county: county)
    City.create(name: 'Lukač', county: county)
    City.create(name: 'Mikleuš', county: county)
    City.create(name: 'Nova Bukovica', county: county)
    City.create(name: 'Orahovica', county: county)
    City.create(name: 'Pitomača', county: county)
    City.create(name: 'Slatina', county: county)
    City.create(name: 'Sopje', county: county)
    City.create(name: 'Suhopolje', county: county)
    City.create(name: 'Špišić Bukovica', county: county)
    City.create(name: 'Virovitica', county: county)
    City.create(name: 'Voćin', county: county)
    City.create(name: 'Zdenci', county: county)
    county = County.create(name: 'XI POŽEŠKO-SLAVONSKA')
    City.create(name: 'Brestovac', county: county)
    City.create(name: 'Čaglin', county: county)
    City.create(name: 'Jakšić', county: county)
    City.create(name: 'Kaptol', county: county)
    City.create(name: 'Kutjevo', county: county)
    City.create(name: 'Lipik', county: county)
    City.create(name: 'Pakrac', county: county)
    City.create(name: 'Pleternica', county: county)
    City.create(name: 'Požega', county: county)
    City.create(name: 'Velika', county: county)
    county = County.create(name: 'XII BRODSKO-POSAVSKA')
    City.create(name: 'Bebrina', county: county)
    City.create(name: 'Brodski Stupnik', county: county)
    City.create(name: 'Bukovlje', county: county)
    City.create(name: 'Cernik', county: county)
    City.create(name: 'Davor', county: county)
    City.create(name: 'Donji Andrijevci', county: county)
    City.create(name: 'Dragalić', county: county)
    City.create(name: 'Garčin', county: county)
    City.create(name: 'Gornja Vrba', county: county)
    City.create(name: 'Gornji Bogićevci', county: county)
    City.create(name: 'Gundinci', county: county)
    City.create(name: 'Klakar', county: county)
    City.create(name: 'Nova Gradiška', county: county)
    City.create(name: 'Nova Kapela', county: county)
    City.create(name: 'Okučani', county: county)
    City.create(name: 'Oprisavci', county: county)
    City.create(name: 'Oriovac', county: county)
    City.create(name: 'Podcrkavlje', county: county)
    City.create(name: 'Rešetari', county: county)
    City.create(name: 'Sibinj', county: county)
    City.create(name: 'Sikirevci', county: county)
    City.create(name: 'Slavonski Brod', county: county)
    City.create(name: 'Slavonski Šamac', county: county)
    City.create(name: 'Stara Gradiška', county: county)
    City.create(name: 'Staro Petrovo Selo', county: county)
    City.create(name: 'Velika Kopanica', county: county)
    City.create(name: 'Vrbje', county: county)
    City.create(name: 'Vrpolje', county: county)
    county = County.create(name: 'XIII ZADARSKA')
    City.create(name: 'Benkovac', county: county)
    City.create(name: 'Bibinje', county: county)
    City.create(name: 'Biograd na Moru', county: county)
    City.create(name: 'Galovac', county: county)
    City.create(name: 'Gračac', county: county)
    City.create(name: 'Jasenice', county: county)
    City.create(name: 'Kali', county: county)
    City.create(name: 'Kolan', county: county)
    City.create(name: 'Kukljica', county: county)
    City.create(name: 'Lišane Ostrovičke', county: county)
    City.create(name: 'Nin', county: county)
    City.create(name: 'Novigrad', county: county)
    City.create(name: 'Obrovac', county: county)
    City.create(name: 'Pag', county: county)
    City.create(name: 'Pakoštane', county: county)
    City.create(name: 'Pašman', county: county)
    City.create(name: 'Polača', county: county)
    City.create(name: 'Poličnik', county: county)
    City.create(name: 'Posedarje', county: county)
    City.create(name: 'Povljana', county: county)
    City.create(name: 'Preko', county: county)
    City.create(name: 'Privlaka', county: county)
    City.create(name: 'Ražanac', county: county)
    City.create(name: 'Sali', county: county)
    City.create(name: 'Stankovci', county: county)
    City.create(name: 'Starigrad', county: county)
    City.create(name: 'Sukošan', county: county)
    City.create(name: 'Sveti Filip i Jakov', county: county)
    City.create(name: 'Škabrnja', county: county)
    City.create(name: 'Tkon', county: county)
    City.create(name: 'Vir', county: county)
    City.create(name: 'Vrsi', county: county)
    City.create(name: 'Zadar', county: county)
    City.create(name: 'Zemunik Donji', county: county)
    county = County.create(name: 'XIV OSJEČKO-BARANJSKA')
    City.create(name: 'Antunovac', county: county)
    City.create(name: 'Beli Manastir', county: county)
    City.create(name: 'Belišće', county: county)
    City.create(name: 'Bilje', county: county)
    City.create(name: 'Bizovac', county: county)
    City.create(name: 'Čeminac', county: county)
    City.create(name: 'Čepin', county: county)
    City.create(name: 'Darda', county: county)
    City.create(name: 'Donja Motičina', county: county)
    City.create(name: 'Donji Miholjac', county: county)
    City.create(name: 'Draž', county: county)
    City.create(name: 'Drenje', county: county)
    City.create(name: 'Đakovo', county: county)
    City.create(name: 'Đurđenovac', county: county)
    City.create(name: 'Erdut', county: county)
    City.create(name: 'Ernestinovo', county: county)
    City.create(name: 'Feričanci', county: county)
    City.create(name: 'Gorjani', county: county)
    City.create(name: 'Jagodnjak', county: county)
    City.create(name: 'Kneževi Vinogradi', county: county)
    City.create(name: 'Koška', county: county)
    City.create(name: 'Levanjska Varoš', county: county)
    City.create(name: 'Magadenovac', county: county)
    City.create(name: 'Marijanci', county: county)
    City.create(name: 'Našice', county: county)
    City.create(name: 'Osijek', county: county)
    City.create(name: 'Petlovac', county: county)
    City.create(name: 'Petrijevci', county: county)
    City.create(name: 'Podgorač', county: county)
    City.create(name: 'Podravska Moslavina', county: county)
    City.create(name: 'Popovac', county: county)
    City.create(name: 'Punitovci', county: county)
    City.create(name: 'Satnica Đakovačka', county: county)
    City.create(name: 'Semeljci', county: county)
    City.create(name: 'Strizivojna', county: county)
    City.create(name: 'Šodolovci', county: county)
    City.create(name: 'Trnava', county: county)
    City.create(name: 'Valpovo', county: county)
    City.create(name: 'Viljevo', county: county)
    City.create(name: 'Viškovci', county: county)
    City.create(name: 'Vladislavci', county: county)
    City.create(name: 'Vuka', county: county)
    county = County.create(name: 'XIX DUBROVAČKO-NERETVANSKA')
    City.create(name: 'Blato', county: county)
    City.create(name: 'Dubrovačko primorje', county: county)
    City.create(name: 'Dubrovnik', county: county)
    City.create(name: 'Janjina', county: county)
    City.create(name: 'Konavle', county: county)
    City.create(name: 'Korčula', county: county)
    City.create(name: 'Kula Norinska', county: county)
    City.create(name: 'Lastovo', county: county)
    City.create(name: 'Lumbarda', county: county)
    City.create(name: 'Metković', county: county)
    City.create(name: 'Mljet', county: county)
    City.create(name: 'Opuzen', county: county)
    City.create(name: 'Orebić', county: county)
    City.create(name: 'Ploče', county: county)
    City.create(name: 'Pojezerje', county: county)
    City.create(name: 'Slivno', county: county)
    City.create(name: 'Smokvica', county: county)
    City.create(name: 'Ston', county: county)
    City.create(name: 'Trpanj', county: county)
    City.create(name: 'Vela Luka', county: county)
    City.create(name: 'Zažablje', county: county)
    City.create(name: 'Župa dubrovačka', county: county)
    county = County.create(name: 'XV ŠIBENSKO-KNINSKA')
    City.create(name: 'Bilice', county: county)
    City.create(name: 'Biskupija', county: county)
    City.create(name: 'Civljane', county: county)
    City.create(name: 'Drniš', county: county)
    City.create(name: 'Ervenik', county: county)
    City.create(name: 'Kijevo', county: county)
    City.create(name: 'Kistanje', county: county)
    City.create(name: 'Knin', county: county)
    City.create(name: 'Murter-Kornati', county: county)
    City.create(name: 'Pirovac', county: county)
    City.create(name: 'Primošten', county: county)
    City.create(name: 'Promina', county: county)
    City.create(name: 'Rogoznica', county: county)
    City.create(name: 'Ružić', county: county)
    City.create(name: 'Skradin', county: county)
    City.create(name: 'Šibenik', county: county)
    City.create(name: 'Tisno', county: county)
    City.create(name: 'Tribunj', county: county)
    City.create(name: 'Unešić', county: county)
    City.create(name: 'Vodice', county: county)
    county = County.create(name: 'XVI VUKOVARSKO-SRIJEMSKA')
    City.create(name: 'Andrijaševci', county: county)
    City.create(name: 'Babina Greda', county: county)
    City.create(name: 'Bogdanovci', county: county)
    City.create(name: 'Borovo', county: county)
    City.create(name: 'Bošnjaci', county: county)
    City.create(name: 'Cerna', county: county)
    City.create(name: 'Drenovci', county: county)
    City.create(name: 'Gradište', county: county)
    City.create(name: 'Gunja', county: county)
    City.create(name: 'Ilok', county: county)
    City.create(name: 'Ivankovo', county: county)
    City.create(name: 'Jarmina', county: county)
    City.create(name: 'Lovas', county: county)
    City.create(name: 'Markušica', county: county)
    City.create(name: 'Negoslavci', county: county)
    City.create(name: 'Nijemci', county: county)
    City.create(name: 'Nuštar', county: county)
    City.create(name: 'Otok', county: county)
    City.create(name: 'Privlaka', county: county)
    City.create(name: 'Stari Jankovci', county: county)
    City.create(name: 'Stari Mikanovci', county: county)
    City.create(name: 'Štitar', county: county)
    City.create(name: 'Tompojevci', county: county)
    City.create(name: 'Tordinci', county: county)
    City.create(name: 'Tovarnik', county: county)
    City.create(name: 'Trpinja', county: county)
    City.create(name: 'Vinkovci', county: county)
    City.create(name: 'Vođinci', county: county)
    City.create(name: 'Vrbanja', county: county)
    City.create(name: 'Vukovar', county: county)
    City.create(name: 'Županja', county: county)
    county = County.create(name: 'XVII SPLITSKO-DALMATINSKA')
    City.create(name: 'Baška Voda', county: county)
    City.create(name: 'Bol', county: county)
    City.create(name: 'Brela', county: county)
    City.create(name: 'Cista Provo', county: county)
    City.create(name: 'Dicmo', county: county)
    City.create(name: 'Dugi Rat', county: county)
    City.create(name: 'Dugopolje', county: county)
    City.create(name: 'Gradac', county: county)
    City.create(name: 'Hrvace', county: county)
    City.create(name: 'Hvar', county: county)
    City.create(name: 'Imotski', county: county)
    City.create(name: 'Jelsa', county: county)
    City.create(name: 'Kaštela', county: county)
    City.create(name: 'Klis', county: county)
    City.create(name: 'Komiža', county: county)
    City.create(name: 'Lećevica', county: county)
    City.create(name: 'Lokvičići', county: county)
    City.create(name: 'Lovreć', county: county)
    City.create(name: 'Makarska', county: county)
    City.create(name: 'Marina', county: county)
    City.create(name: 'Milna', county: county)
    City.create(name: 'Muć', county: county)
    City.create(name: 'Nerežišća', county: county)
    City.create(name: 'Okrug', county: county)
    City.create(name: 'Omiš', county: county)
    City.create(name: 'Otok', county: county)
    City.create(name: 'Podbablje', county: county)
    City.create(name: 'Podgora', county: county)
    City.create(name: 'Podstrana', county: county)
    City.create(name: 'Postira', county: county)
    City.create(name: 'Prgomet', county: county)
    City.create(name: 'Primorski Dolac', county: county)
    City.create(name: 'Proložac', county: county)
    City.create(name: 'Pučišća', county: county)
    City.create(name: 'Runovići', county: county)
    City.create(name: 'Seget', county: county)
    City.create(name: 'Selca', county: county)
    City.create(name: 'Sinj', county: county)
    City.create(name: 'Solin', county: county)
    City.create(name: 'Split', county: county)
    City.create(name: 'Stari Grad', county: county)
    City.create(name: 'Sućuraj', county: county)
    City.create(name: 'Supetar', county: county)
    City.create(name: 'Sutivan', county: county)
    City.create(name: 'Šestanovac', county: county)
    City.create(name: 'Šolta', county: county)
    City.create(name: 'Trilj', county: county)
    City.create(name: 'Trogir', county: county)
    City.create(name: 'Tučepi', county: county)
    City.create(name: 'Vis', county: county)
    City.create(name: 'Vrgorac', county: county)
    City.create(name: 'Vrlika', county: county)
    City.create(name: 'Zadvarje', county: county)
    City.create(name: 'Zagvozd', county: county)
    City.create(name: 'Zmijavci', county: county)
    county = County.create(name: 'XVIII ISTARSKA')
    City.create(name: 'Bale-Valle', county: county)
    City.create(name: 'Barban', county: county)
    City.create(name: 'Brtonigla-Verteneglio', county: county)
    City.create(name: 'Buje-Buie', county: county)
    City.create(name: 'Buzet', county: county)
    City.create(name: 'Cerovlje', county: county)
    City.create(name: 'Fažana-Fasana', county: county)
    City.create(name: 'Funtana-Fontane', county: county)
    City.create(name: 'Gračišće', county: county)
    City.create(name: 'Grožnjan-Grisignana', county: county)
    City.create(name: 'Kanfanar', county: county)
    City.create(name: 'Karojba', county: county)
    City.create(name: 'Kaštelir-Labinci-Castelliere-S. Domenica', county: county)
    City.create(name: 'Kršan', county: county)
    City.create(name: 'Labin', county: county)
    City.create(name: 'Lanišće', county: county)
    City.create(name: 'Ližnjan-Lisignano', county: county)
    City.create(name: 'Lupoglav', county: county)
    City.create(name: 'Marčana', county: county)
    City.create(name: 'Medulin', county: county)
    City.create(name: 'Motovun-Montona', county: county)
    City.create(name: 'Novigrad-Cittanova', county: county)
    City.create(name: 'Oprtalj-Portole', county: county)
    City.create(name: 'Pazin', county: county)
    City.create(name: 'Pićan', county: county)
    City.create(name: 'Poreč-Parenzo', county: county)
    City.create(name: 'Pula-Pola', county: county)
    City.create(name: 'Raša', county: county)
    City.create(name: 'Rovinj-Rovigno', county: county)
    City.create(name: 'Sveta Nedelja', county: county)
    City.create(name: 'Sveti Lovreč', county: county)
    City.create(name: 'Sveti Petar u Šumi', county: county)
    City.create(name: 'Svetvinčenat', county: county)
    City.create(name: 'Tar-Vabriga-Torre Abrega', county: county)
    City.create(name: 'Tinjan', county: county)
    City.create(name: 'Umag-Umago', county: county)
    City.create(name: 'Višnjan-Visignano', county: county)
    City.create(name: 'Vižinada-Visinada', county: county)
    City.create(name: 'Vodnjan-Dignano', county: county)
    City.create(name: 'Vrsar-Orsera', county: county)
    City.create(name: 'Žminj', county: county)
    county = County.create(name: 'XX MEĐIMURSKA')
    City.create(name: 'Belica', county: county)
    City.create(name: 'Čakovec', county: county)
    City.create(name: 'Dekanovec', county: county)
    City.create(name: 'Domašinec', county: county)
    City.create(name: 'Donja Dubrava', county: county)
    City.create(name: 'Donji Kraljevec', county: county)
    City.create(name: 'Donji Vidovec', county: county)
    City.create(name: 'Goričan', county: county)
    City.create(name: 'Gornji Mihaljevec', county: county)
    City.create(name: 'Kotoriba', county: county)
    City.create(name: 'Mala Subotica', county: county)
    City.create(name: 'Mursko Središće', county: county)
    City.create(name: 'Nedelišće', county: county)
    City.create(name: 'Orehovica', county: county)
    City.create(name: 'Podturen', county: county)
    City.create(name: 'Prelog', county: county)
    City.create(name: 'Pribislavec', county: county)
    City.create(name: 'Selnica', county: county)
    City.create(name: 'Strahoninec', county: county)
    City.create(name: 'Sveta Marija', county: county)
    City.create(name: 'Sveti Juraj na Bregu', county: county)
    City.create(name: 'Sveti Martin na Muri', county: county)
    City.create(name: 'Šenkovec', county: county)
    City.create(name: 'Štrigova', county: county)
    City.create(name: 'Vratišinec', county: county)
    county = County.create(name: 'XXI GRAD ZAGREB')
    City.create(name: 'Zagreb', county: county)
  end

end
